"""add subscription fields to clinic

Revision ID: 57fb01e86a15
Revises: 
Create Date: 2026-05-09 15:22:55.411046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57fb01e86a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.create_foreign_key(None, 'allopathy_rx', 'visits', ['visit_id'], ['id'])
    op.add_column('clinics', sa.Column('clinic_type', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('subscription_period', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.add_column('clinics', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('clinics', sa.Column('max_patients_per_month', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('max_staff', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('max_doctors', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('has_logo', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('has_signature', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('has_whatsapp', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('has_first_patient', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('has_first_consultation', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('onboarding_dismissed', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_follow_ups_clinic_status'), table_name='follow_ups')
    op.drop_index(op.f('idx_follow_ups_due_date'), table_name='follow_ups')
    op.drop_index(op.f('idx_follow_ups_due_status'), table_name='follow_ups')
    op.drop_index(op.f('idx_follow_ups_patient_id'), table_name='follow_ups')
    op.drop_index(op.f('idx_follow_ups_status'), table_name='follow_ups')
    op.create_foreign_key(None, 'homeopathy_cases', 'visits', ['visit_id'], ['id'])
    op.drop_index(op.f('idx_patients_clinic_id'), table_name='patients')
    op.drop_index(op.f('idx_patients_phone'), table_name='patients')
    op.drop_index(op.f('idx_payments_created_at'), table_name='payments')
    op.drop_index(op.f('idx_payments_visit_id'), table_name='payments')
    op.create_foreign_key(None, 'payments', 'visits', ['visit_id'], ['id'])
    op.alter_column('queue', 'appointment_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('queue', 'visit_type',
               existing_type=postgresql.ENUM('WALKIN', 'APPOINTMENT', name='visittypequeue'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('queue', 'status',
               existing_type=postgresql.ENUM('WAITING', 'IN_TREATMENT', 'COMPLETED', 'NO_SHOW', 'SKIPPED', name='queuestatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DOCTOR', 'RECEPTIONIST', name='userrole'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.add_column('visits', sa.Column('visit_status', sa.String(), nullable=True))
    op.drop_index(op.f('idx_visits_clinic_id'), table_name='visits')
    op.drop_index(op.f('idx_visits_doctor_id'), table_name='visits')
    op.drop_index(op.f('idx_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('idx_visits_payment_status'), table_name='visits')
    op.drop_index(op.f('idx_visits_type'), table_name='visits')
    op.drop_index(op.f('idx_visits_visit_date'), table_name='visits')
    op.create_index(op.f('ix_visits_visit_status'), 'visits', ['visit_status'], unique=False)
    op.create_foreign_key(None, 'vitals', 'visits', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals', type_='foreignkey')
    op.drop_index(op.f('ix_visits_visit_status'), table_name='visits')
    op.create_index(op.f('idx_visits_visit_date'), 'visits', ['visit_date'], unique=False)
    op.create_index(op.f('idx_visits_type'), 'visits', ['type'], unique=False)
    op.create_index(op.f('idx_visits_payment_status'), 'visits', ['payment_status'], unique=False)
    op.create_index(op.f('idx_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index(op.f('idx_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('idx_visits_clinic_id'), 'visits', ['clinic_id'], unique=False)
    op.drop_column('visits', 'visit_status')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DOCTOR', 'RECEPTIONIST', name='userrole'),
               nullable=True)
    op.alter_column('queue', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('WAITING', 'IN_TREATMENT', 'COMPLETED', 'NO_SHOW', 'SKIPPED', name='queuestatus'),
               existing_nullable=True)
    op.alter_column('queue', 'visit_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('WALKIN', 'APPOINTMENT', name='visittypequeue'),
               existing_nullable=True)
    op.alter_column('queue', 'appointment_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_index(op.f('idx_payments_visit_id'), 'payments', ['visit_id'], unique=False)
    op.create_index(op.f('idx_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('idx_patients_phone'), 'patients', ['phone_mobile'], unique=False)
    op.create_index(op.f('idx_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.drop_constraint(None, 'homeopathy_cases', type_='foreignkey')
    op.create_index(op.f('idx_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_index(op.f('idx_follow_ups_patient_id'), 'follow_ups', ['patient_id'], unique=False)
    op.create_index(op.f('idx_follow_ups_due_status'), 'follow_ups', ['due_date', 'status'], unique=False)
    op.create_index(op.f('idx_follow_ups_due_date'), 'follow_ups', ['due_date'], unique=False)
    op.create_index(op.f('idx_follow_ups_clinic_status'), 'follow_ups', ['clinic_id', 'status'], unique=False)
    op.drop_column('clinics', 'onboarding_dismissed')
    op.drop_column('clinics', 'has_first_consultation')
    op.drop_column('clinics', 'has_first_patient')
    op.drop_column('clinics', 'has_whatsapp')
    op.drop_column('clinics', 'has_signature')
    op.drop_column('clinics', 'has_logo')
    op.drop_column('clinics', 'onboarding_complete')
    op.drop_column('clinics', 'max_doctors')
    op.drop_column('clinics', 'max_staff')
    op.drop_column('clinics', 'max_patients_per_month')
    op.drop_column('clinics', 'subscription_start_date')
    op.drop_column('clinics', 'razorpay_subscription_id')
    op.drop_column('clinics', 'subscription_period')
    op.drop_column('clinics', 'subscription_plan')
    op.drop_column('clinics', 'clinic_type')
    op.drop_constraint(None, 'allopathy_rx', type_='foreignkey')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
